"""removed review_id in rentals

Revision ID: 6d4347dbcf22
Revises: f1ca6c98878d
Create Date: 2024-05-14 13:40:29.138306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4347dbcf22'
down_revision = 'f1ca6c98878d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rentals_review_id_reviews', type_='foreignkey')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_rentals_review_id_reviews', 'reviews', ['review_id'], ['id'])

    # ### end Alembic commands ###
