"""changed in_stock from rentals to instruments

Revision ID: f1ca6c98878d
Revises: 73fe12700b9b
Create Date: 2024-05-13 22:44:57.278890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ca6c98878d'
down_revision = '73fe12700b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), nullable=True))

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###
